[ApiHttp]
Addr = "0.0.0.0"
Port = 8081
JwtSecret = "secret"

[Qiniu]
QINIU_SK=""
QINIU_AK=""
QINIU_BUKET_PATH=""
QINIU_HOST=""
QINIU_UPLOAD_URL=""
QINIU_UPLOAD_DIR=""

[IMRpcService]
Addr = ""
Port = 8092
Name = "im_rpc_server"

[MySql]
Host = ""
Port = 3306
Username = ""
Password = ""
Db = ""
Charset = ""

[Redis]
Host = "127.0.0.1"
Port = 6378
Password = ""
Db = 9